source 'https://cdn.cocoapods.org/'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

platform :ios, '13.0'

load 'remove_ios_only_frameworks.rb'

target 'learnX' do
  use_unimodules!(exclude: [
    'expo-asset',
    'expo-constants',
    'expo-image-loader',
    'expo-permissions',
    'unimodules-app-loader',
    'unimodules-barcode-scanner-interface',
    'unimodules-camera-interface',
    'unimodules-constants-interface',
    'unimodules-face-detector-interface',
    'unimodules-image-loader-interface',
    'unimodules-sensors-interface',
    'unimodules-task-manager-interface'
  ])

  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => true
  )
end

def catalyst_unsupported_pods
  []
end

post_install do |installer|
  react_native_post_install(installer)

  installer.pods_project.targets.each do |target|
    if target.respond_to?(:product_type) and target.product_type == 'com.apple.product-type.bundle'
      target.build_configurations.each do |config|
        config.build_settings['CODE_SIGN_IDENTITY[sdk=macosx*]'] = '-'
      end
    end
  end

  `sed -i -e  $'s/__IPHONE_10_0/__IPHONE_14_0/' #{installer.sandbox.root}/RCT-Folly/folly/portability/Time.h`

  installer.configure_support_catalyst
end
