update_fastlane

platform :ios do
  # iOS Lanes

  before_all do
    setup_travis
  end

  desc 'Fetch certificates and provisioning profiles.'
  lane :certificates do
    match(app_identifier: 'io.robertying.learnX', type: 'development', readonly: is_ci)
    match(app_identifier: 'io.robertying.learnX', type: 'appstore', readonly: is_ci)
  end

  desc 'Build the iOS application.'
  lane :build do
    certificates
    increment_build_number(xcodeproj: 'ios/learnX.xcodeproj')
    gym(scheme: 'learnX', workspace: 'ios/learnX.xcworkspace')
  end

  desc 'Ship to Testflight.'
  lane :beta do
    build
    upload_to_testflight(username: "yingrui205@qq.com", skip_waiting_for_build_processing: true)
  end
end

platform :android do
  # Android Lanes

  desc 'Build the Android application.'
  lane :build do
    gradle(task: 'clean', project_dir: 'android/')
    gradle(task: 'assemble', build_type: 'Release', project_dir: 'android/')
  end

  desc 'Ship to Google Play Beta.'
  lane :beta do
    gradle(task: 'bundle', build_type: 'Release', project_dir: 'android/')
    upload_to_play_store(track: 'beta', skip_upload_apk: true)
  end
end
