update_fastlane
setup_travis

platform :ios do
  # iOS Lanes

  desc 'Fetch certificates and provisioning profiles.'
  lane :certificates do
    match(app_identifier: 'io.robertying.learnX', type: 'development', readonly: is_ci)
    match(app_identifier: 'io.robertying.learnX', type: 'appstore', readonly: is_ci)
  end

  desc 'Build the iOS application.'
  private_lane :build do
    certificates
    increment_build_number(xcodeproj: 'ios/learnX.xcodeproj')
    gym(scheme: 'learnX', workspace: 'ios/learnX.xcworkspace')
  end

  desc 'Ship to Testflight.'
  lane :beta do
    build
    upload_to_testflight(username: "yingrui205@qq.com")
  end
end

platform :android do
  # Android Lanes

  desc 'Build the Android application.'
  private_lane :build do
    gradle(task: 'clean', project_dir: 'android/')
    gradle(task: 'assemble', build_type: 'Release', project_dir: 'android/')
  end

  desc 'Ship to Beta.'
  lane :beta do
    gradle(task: 'assemble', build_type: 'Release', project_dir: 'android/')
    crashlytics
  end
end
