export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const GET_ALL_SEMESTERS_REQUEST = "GET_ALL_SEMESTERS_REQUEST";
export const GET_ALL_SEMESTERS_SUCCESS = "GET_ALL_SEMESTERS_SUCCESS";
export const GET_ALL_SEMESTERS_FAILURE = "GET_ALL_SEMESTERS_FAILURE";

export const GET_CURRENT_SEMESTER = "GET_CURRENT_SEMESTER";
export const SET_CURRENT_SEMESTER = "SET_CURRENT_SEMESTER";

export const GET_COURSES_FOR_SEMESTER_REQUEST =
  "GET_COURSES_FOR_SEMESTER_REQUEST";
export const GET_COURSES_FOR_SEMESTER_SUCCESS =
  "GET_COURSES_FOR_SEMESTER_SUCCESS";
export const GET_COURSES_FOR_SEMESTER_FAILURE =
  "GET_COURSES_FOR_SEMESTER_FAILURE";

export const GET_NOTICES_FOR_COURSE_REQUEST = "GET_NOTICES_FOR_COURSE_REQUEST";
export const GET_NOTICES_FOR_COURSE_SUCCESS = "GET_NOTICES_FOR_COURSE_SUCCESS";
export const GET_NOTICES_FOR_COURSE_FAILURE = "GET_NOTICES_FOR_COURSE_FAILURE";

export const GET_FILES_FOR_COURSE_REQUEST = "GET_FILES_FOR_COURSE_REQUEST";
export const GET_FILES_FOR_COURSE_SUCCESS = "GET_FILES_FOR_COURSE_SUCCESS";
export const GET_FILES_FOR_COURSE_FAILURE = "GET_FILES_FOR_COURSE_FAILURE";

export const GET_ASSIGNMENTS_FOR_COURSE_REQUEST =
  "GET_ASSIGNMENTS_FOR_COURSE_REQUEST";
export const GET_ASSIGNMENTS_FOR_COURSE_SUCCESS =
  "GET_ASSIGNMENTS_FOR_COURSE_SUCCESS";
export const GET_ASSIGNMENTS_FOR_COURSE_FAILURE =
  "GET_ASSIGNMENTS_FOR_COURSE_FAILURE";

export const GET_ALL_NOTICES_FOR_COURSES_REQUEST =
  "GET_ALL_NOTICES_FOR_COURSES_REQUEST";
export const GET_ALL_NOTICES_FOR_COURSES_SUCCESS =
  "GET_ALL_NOTICES_FOR_COURSES_SUCCESS";
export const GET_ALL_NOTICES_FOR_COURSES_FAILURE =
  "GET_ALL_NOTICES_FOR_COURSES_FAILURE";

export const GET_ALL_FILES_FOR_COURSES_REQUEST =
  "GET_ALL_FILES_FOR_COURSES_REQUEST";
export const GET_ALL_FILES_FOR_COURSES_SUCCESS =
  "GET_ALL_FILES_FOR_COURSES_SUCCESS";
export const GET_ALL_FILES_FOR_COURSES_FAILURE =
  "GET_ALL_FILES_FOR_COURSES_FAILURE";

export const GET_ALL_ASSIGNMENTS_FOR_COURSES_REQUEST =
  "GET_ALL_ASSIGNMENTS_FOR_COURSES_REQUEST";
export const GET_ALL_ASSIGNMENTS_FOR_COURSES_SUCCESS =
  "GET_ALL_ASSIGNMENTS_FOR_COURSES_SUCCESS";
export const GET_ALL_ASSIGNMENTS_FOR_COURSES_FAILURE =
  "GET_ALL_ASSIGNMENTS_FOR_COURSES_FAILURE";

export const SHOW_TOAST = "SHOW_TOAST";
export const HIDE_TOAST = "HIDE_TOAST";

export const PIN_NOTICE = "PIN_NOTICE";
export const UNPIN_NOTICE = "UNPIN_NOTICE";

export const PIN_FILE = "PIN_FILE";
export const UNPIN_FILE = "UNPIN_FILE";

export const PIN_ASSIGNMENT = "PIN_ASSIGNMENT";
export const UNPIN_ASSIGNMENT = "UNPIN_ASSIGNMENT";

export const PIN_COURSE = "PIN_COURSE";
export const UNPIN_COURSE = "UNPIN_COURSE";

export const SET_COURSES_FILTER = "SET_COURSES_FILTER";

export const SET_TABS_ORDER = "SET_TABS_ORDER";
export const SET_AUTO_REFRESHING = "SET_AUTO_REFRESHING";
export const SET_CALENDAR_SYNC = "SET_CALENDAR_SYNC";
export const SET_CALENDAR_ID = "SET_CALENDAR_ID";
export const SET_EVENT_ID_FOR_ASSIGNMENT = "SET_EVENT_ID_FOR_ASSIGNMENT";
export const CLEAR_EVENT_IDS = "CLEAR_EVENT_IDS";

export const CLEAR_STORE = "CLEAR_STORE";
export const SET_MOCK_STORE = "SET_MOCK_STORE";

export const SET_UPDATE = "SET_UPDATE";

export const SET_WINDOW = "SET_WINDOW";

export const SET_NOTIFICATIONS = "SET_NOTIFICATIONS";
export const SET_NOTIFICATION_TYPES = "SET_NOTIFICATION_TYPES";

export const SET_LANG = "SET_LANG";
