export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const GET_ALL_SEMESTERS_REQUEST = 'GET_ALL_SEMESTERS_REQUEST';
export const GET_ALL_SEMESTERS_SUCCESS = 'GET_ALL_SEMESTERS_SUCCESS';
export const GET_ALL_SEMESTERS_FAILURE = 'GET_ALL_SEMESTERS_FAILURE';

export const SET_CURRENT_SEMESTER = 'SET_CURRENT_SEMESTER';

export const GET_COURSES_FOR_SEMESTER_REQUEST =
  'GET_COURSES_FOR_SEMESTER_REQUEST';
export const GET_COURSES_FOR_SEMESTER_SUCCESS =
  'GET_COURSES_FOR_SEMESTER_SUCCESS';
export const GET_COURSES_FOR_SEMESTER_FAILURE =
  'GET_COURSES_FOR_SEMESTER_FAILURE';

export const GET_NOTICES_FOR_COURSE_REQUEST = 'GET_NOTICES_FOR_COURSE_REQUEST';
export const GET_NOTICES_FOR_COURSE_SUCCESS = 'GET_NOTICES_FOR_COURSE_SUCCESS';
export const GET_NOTICES_FOR_COURSE_FAILURE = 'GET_NOTICES_FOR_COURSE_FAILURE';

export const GET_FILES_FOR_COURSE_REQUEST = 'GET_FILES_FOR_COURSE_REQUEST';
export const GET_FILES_FOR_COURSE_SUCCESS = 'GET_FILES_FOR_COURSE_SUCCESS';
export const GET_FILES_FOR_COURSE_FAILURE = 'GET_FILES_FOR_COURSE_FAILURE';

export const GET_ASSIGNMENTS_FOR_COURSE_REQUEST =
  'GET_ASSIGNMENTS_FOR_COURSE_REQUEST';
export const GET_ASSIGNMENTS_FOR_COURSE_SUCCESS =
  'GET_ASSIGNMENTS_FOR_COURSE_SUCCESS';
export const GET_ASSIGNMENTS_FOR_COURSE_FAILURE =
  'GET_ASSIGNMENTS_FOR_COURSE_FAILURE';

export const GET_ALL_NOTICES_FOR_COURSES_REQUEST =
  'GET_ALL_NOTICES_FOR_COURSES_REQUEST';
export const GET_ALL_NOTICES_FOR_COURSES_SUCCESS =
  'GET_ALL_NOTICES_FOR_COURSES_SUCCESS';
export const GET_ALL_NOTICES_FOR_COURSES_FAILURE =
  'GET_ALL_NOTICES_FOR_COURSES_FAILURE';

export const GET_ALL_FILES_FOR_COURSES_REQUEST =
  'GET_ALL_FILES_FOR_COURSES_REQUEST';
export const GET_ALL_FILES_FOR_COURSES_SUCCESS =
  'GET_ALL_FILES_FOR_COURSES_SUCCESS';
export const GET_ALL_FILES_FOR_COURSES_FAILURE =
  'GET_ALL_FILES_FOR_COURSES_FAILURE';

export const GET_ALL_ASSIGNMENTS_FOR_COURSES_REQUEST =
  'GET_ALL_ASSIGNMENTS_FOR_COURSES_REQUEST';
export const GET_ALL_ASSIGNMENTS_FOR_COURSES_SUCCESS =
  'GET_ALL_ASSIGNMENTS_FOR_COURSES_SUCCESS';
export const GET_ALL_ASSIGNMENTS_FOR_COURSES_FAILURE =
  'GET_ALL_ASSIGNMENTS_FOR_COURSES_FAILURE';

export const PIN_NOTICE = 'PIN_NOTICE';
export const UNPIN_NOTICE = 'UNPIN_NOTICE';
export const PIN_FILE = 'PIN_FILE';
export const UNPIN_FILE = 'UNPIN_FILE';
export const PIN_ASSIGNMENT = 'PIN_ASSIGNMENT';
export const UNPIN_ASSIGNMENT = 'UNPIN_ASSIGNMENT';
export const PIN_COURSE = 'PIN_COURSE';
export const UNPIN_COURSE = 'UNPIN_COURSE';

export const FAV_NOTICE = 'FAV_NOTICE';
export const UNFAV_NOTICE = 'UNFAV_NOTICE';
export const FAV_FILE = 'FAV_FILE';
export const UNFAV_FILE = 'UNFAV_FILE';
export const FAV_ASSIGNMENT = 'FAV_ASSIGNMENT';
export const UNFAV_ASSIGNMENT = 'UNFAV_ASSIGNMENT';
export const FAV_COURSE = 'FAV_COURSE';
export const UNFAV_COURSE = 'UNFAV_COURSE';

export const READ_NOTICE = 'READ_NOTICE';
export const UNREAD_NOTICE = 'UNREAD_NOTICE';
export const READ_FILE = 'READ_FILE';
export const UNREAD_FILE = 'UNREAD_FILE';
export const READ_ASSIGNMENT = 'READ_ASSIGNMENT';
export const UNREAD_ASSIGNMENT = 'UNREAD_ASSIGNMENT';

export const HIDE_COURSE = 'HIDE_COURSE';
export const UNHIDE_COURSE = 'UNHIDE_COURSE';

export const SET_SETTING = 'SET_SETTING';
export const SET_EVENT_ID_FOR_ASSIGNMENT = 'SET_EVENT_ID_FOR_ASSIGNMENT';
export const CLEAR_EVENT_IDS = 'CLEAR_EVENT_IDS';

export const RESET_LOADING = 'RESET_LOADING';
export const CLEAR_STORE = 'CLEAR_STORE';
export const SET_MOCK_STORE = 'SET_MOCK_STORE';
