theme: jekyll-theme-cayman
description_cn: 清华大学网络学堂 App，以 React Native 构建
show_downloads: true
ios_url: "https://itunes.apple.com/cn/app/learnx-thu-web-learning/id1459073115?ls=1&mt=8"
android_url: "https://github.com/robertying/learnX/releases/latest"
